# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print('numpy version:', np.__version__)
np.show_config()

numpy version: 1.26.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/glebk/miniconda3/envs/conda/Library/include
    lib directory: C:/Users/glebk/miniconda3/envs/conda/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/glebk/miniconda3/envs/conda/Library/include
    lib directory: C:/Users/glebk/miniconda3/envs/conda/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
np.zeros(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_vector = np.zeros(10)
null_vector[5] = 1
print(null_vector)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector = np.arange(0, 10)
np.flip(vector, 0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
array = np.array([1,2,0,0,4,0])
print(np.nonzero(array))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
rng = np.random.default_rng()
rng.integers(10, 100, size=(3, 3, 3))

array([[[20, 57, 75],
        [29, 36, 28],
        [70, 86, 32]],

       [[37, 98, 21],
        [66, 14, 44],
        [94, 58, 64]],

       [[30, 62, 75],
        [60, 17, 15],
        [74, 80, 26]]], dtype=int64)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
matrix = rng.integers(100, 1000, size=(10, 10))
print(matrix)
print('min value:', np.min(matrix))
print('max value', np.max(matrix))

[[748 449 142 164 435 522 531 261 823 401]
 [622 992 270 331 670 755 249 696 588 391]
 [995 751 170 589 349 114 173 287 830 343]
 [703 124 251 612 475 768 216 134 160 204]
 [149 341 823 823 894 898 891 830 884 570]
 [145 580 185 792 884 737 200 597 225 755]
 [818 496 265 278 961 390 670 241 313 364]
 [989 338 242 136 314 365 107 690 763 696]
 [946 134 225 247 214 861 178 681 568 110]
 [715 687 544 772 933 653 649 289 764 566]]
min value: 107
max value 995


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
vector = rng.integers(10, 100, size=30)
print('vector:', vector)
print('mean:', np.mean(vector))

vector: [55 52 15 90 20 92 65 65 70 72 40 48 68 23 84 86 22 19 39 31 16 70 93 52
 74 74 46 76 88 68]
mean: 57.1


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
matrix = np.zeros((10, 10))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
matrix = vector = rng.integers(10, 100, size=(10, 10))
matrix[:, [0, -1]] = 0
matrix[[0, -1], :] = 0
print(matrix)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0 50 89 33 63 89 15 76 63  0]
 [ 0 24 25 24 31 98 86 72 44  0]
 [ 0 41 75 89 19 97 18 34 24  0]
 [ 0 50 66 26 26 62 49 72 63  0]
 [ 0 36 41 80 26 53 35 23 81  0]
 [ 0 29 79 87 44 15 74 84 99  0]
 [ 0 12 56 64 65 62 49 36 56  0]
 [ 0 62 87 92 30 80 11 38 26  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
chess_board = np.zeros((8, 8))
chess_board[1::2, ::2] = 1
chess_board[::2, 1::2] = 1
print(chess_board)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
array = np.zeros((6, 7, 8))
np.unravel_index(100, array.shape)

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
chess_board_pattern = np.array([[0, 1], [1, 0]])
chess_board = np.tile(chess_board_pattern, (4, 4))
print(chess_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
matrix = rng.integers(10, 100, size=(5, 5))
mean = np.mean(matrix)
deviation = np.std(matrix)
normalized_matrix = (matrix - mean / deviation)
print(normalized_matrix)

[[51.78643269 96.78643269  8.78643269 42.78643269 28.78643269]
 [47.78643269  7.78643269 64.78643269 35.78643269 35.78643269]
 [82.78643269 47.78643269 22.78643269 18.78643269 90.78643269]
 [44.78643269 62.78643269 59.78643269 58.78643269 71.78643269]
 [44.78643269 24.78643269 80.78643269 61.78643269 67.78643269]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
matrix1 = rng.integers(0, 10, size=(5, 3))
matrix2 = rng.integers(0, 10, size=(3, 2))
np.dot(matrix1, matrix2)

array([[21, 64],
       [14, 42],
       [ 6, 28],
       [29, 92],
       [ 8, 44]], dtype=int64)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
vector = np.arange(1, 12)
vector[(3 < vector) & (vector < 8)] *= -1
print(vector)

[ 1  2  3 -4 -5 -6 -7  8  9 10 11]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9
<br>10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

All execept last one

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan
<br>0
<br>[0.]

#### 29. How to round away from zero a float array ? (★☆☆)

In [26]:
float_array = np.array([0.4, 4.6, -3.2, 6.3])
np.ceil(float_array)

array([ 1.,  5., -3.,  7.])

#### 30. How to find common values between two arrays? (★☆☆)

In [27]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
np.intersect1d(array1, array2)

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [28]:
import warnings

#disabling warnings
warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)
warnings.filterwarnings("ignore", category=np.RankWarning)

#restore to default
warnings.filterwarnings("default")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

The expression return False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [29]:
from datetime import datetime, timedelta
today = datetime.now().date()
print('today:', today)
print('yesterday', today - timedelta(days=1))
print('tommorow', today + timedelta(days=1))

today: 2023-11-02
yesterday 2023-11-01
tommorow 2023-11-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [30]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [31]:
A = np.ones(3) * 1
B = np.ones(3) * 2
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(B, A, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [32]:
array = np.round(rng.uniform(0, 100, 10), 1)
array = array[array == array.astype(int)]
print(array)

[16.  1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [33]:
matrix = np.zeros((5, 5))
matrix += np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [34]:
def generator():
    for i in range (10):
        yield i
np.fromiter(generator(), dtype=int, count=-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [35]:
rng.random(10)

array([0.43344546, 0.78698252, 0.56712237, 0.02490374, 0.61490281,
       0.84871134, 0.1902399 , 0.29259892, 0.35003607, 0.48954987])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [36]:
vector = rng.integers(0, 10, 10)
np.sort(vector)

array([0, 2, 3, 4, 4, 4, 6, 7, 8, 8], dtype=int64)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [37]:
array = np.arange(10)
np.add.reduce(array)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [38]:
A = rng.integers(0, 2, 4)
B = rng.integers(0, 2, 4)
print(A)
print(B)
np.array_equal(A, B)

[1 0 1 1]
[1 0 1 0]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [39]:
array = np.arange(10)
array.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [40]:
cartesian = np.random.random((10,2))
X = cartesian[:,0]
Y = cartesian[:,1]
distances = np.sqrt(X**2+Y**2)
angles = np.arctan2(Y,X)
print(distances)
print(angles)

[0.63209939 0.90677679 0.34997114 0.53662049 0.30339482 1.12677838
 0.3961927  0.6624786  0.66780401 1.00989446]
[0.21637911 0.90819657 0.81221433 0.00568983 0.86103813 0.98532034
 0.68359585 0.08404688 0.60899266 0.45068945]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [41]:
vector = rng.integers(0, 10, 10)
print(vector)
vector[vector.argmax()] = 0
print(vector)

[5 1 3 2 6 0 9 9 8 1]
[5 1 3 2 6 0 0 9 8 1]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [42]:
array = np.zeros((5,5), [('x',float),('y',float)])
array['x'], array['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [43]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [44]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [45]:
array = np.arange(100)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [46]:
vector = np.arange(100)
scalar = 13.2
index = np.abs(vector - scalar).argmin()
print(vector[index])

13


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [47]:
rgb_array = np.empty((100, 3), dtype=int)
for i in range(100):
    rgb_array[i] = rng.integers(0, 256, 3)
print(rgb_array)

[[  5  89  88]
 [ 97  81 203]
 [143  18 220]
 [194 100  26]
 [174 136 211]
 [  0  51  29]
 [118  76  13]
 [135 221 244]
 [217 100 172]
 [224  21 152]
 [217 207 209]
 [159 181 146]
 [173 200 114]
 [160  40 168]
 [ 78 206 249]
 [140  63  64]
 [113 202 151]
 [174 170  58]
 [102 142 234]
 [ 94 100   7]
 [157   4 189]
 [103 252   4]
 [207  82 127]
 [172 255  42]
 [227   3 239]
 [178  26  12]
 [227 182 106]
 [173 104  53]
 [ 30 203 135]
 [245  17 168]
 [ 13 253 114]
 [218  34 160]
 [ 37 226 215]
 [174 118 200]
 [ 97 220 237]
 [ 14  37 152]
 [ 73 112 143]
 [166  21 232]
 [100 229 181]
 [192 217 100]
 [ 59  12  51]
 [123 146  99]
 [179 191 193]
 [128 183  20]
 [200 213   4]
 [254  57 242]
 [154 231 171]
 [168  66  92]
 [235 137 122]
 [207  95  84]
 [139 195 185]
 [247 252  83]
 [  4  74  25]
 [232 169 205]
 [ 20 232 121]
 [ 13 155 194]
 [ 17 157 133]
 [ 97  99 133]
 [  0  64  47]
 [177 213  71]
 [194  42 226]
 [128   7 210]
 [ 96 110 103]
 [ 39 224  92]
 [165  90 230]
 [114 210  42]
 [145 253 

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [48]:
coordinates = rng.integers(-10, 10, size=(10, 2))
X,Y = np.atleast_2d(coordinates[:,0], coordinates[:,1])
distances = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(distances)

[[ 0.          7.61577311  8.48528137 10.29563014 18.97366596  7.28010989
  10.44030651 14.4222051   6.70820393 18.24828759]
 [ 7.61577311  0.          3.16227766  6.32455532 11.40175425 11.18033989
   8.06225775  7.07106781  9.8488578  12.52996409]
 [ 8.48528137  3.16227766  0.          3.16227766 12.         13.60147051
   5.          6.32455532 12.36931688 15.        ]
 [10.29563014  6.32455532  3.16227766  0.         13.34166406 16.2788206
   2.23606798  7.07106781 15.13274595 17.69180601]
 [18.97366596 11.40175425 12.         13.34166406  0.         20.61552813
  15.5241747   6.32455532 19.20937271  9.        ]
 [ 7.28010989 11.18033989 13.60147051 16.2788206  20.61552813  0.
  17.02938637 18.02775638  1.41421356 16.4924225 ]
 [10.44030651  8.06225775  5.          2.23606798 15.5241747  17.02938637
   0.          9.21954446 16.         19.84943324]
 [14.4222051   7.07106781  6.32455532  7.07106781  6.32455532 18.02775638
   9.21954446  0.         16.64331698 12.52996409]
 [ 6.7082

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [49]:
float_array = rng.uniform(1, 100, 100).astype(np.float32)
int_array = float_array.round().astype(np.int32)
print(int_array)

[37 69 87 51 64 80 78 57 15  9 71  8 90 42 81 72 27 27 18 88 61 84 65 20
 51 35 17 92 68 87  4 88 43  7 82 77 99 47 11  9  3 93 58 38 73  6 66 93
  2 55 55 39 71 75 47 92 50 51 55 30 31  4 75 20 97  2 10 35 83 87  7 53
  7 97 16 29 60 63 91 58 97 47 63 53 34 20  9 72 78 98 49 55 10 61 67 65
 13 61 47 62]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [50]:
from io import StringIO

string = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
array = np.genfromtxt(string, delimiter=",", dtype=np.int32)
print(array)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [51]:
array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(array):
    print(index, value)
for index in np.ndindex(array.shape):
    print(index, array[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [52]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [53]:
p_elements = np.arange(100)
for i in range(100):
    p_elements[rng.integers(100)] = p_elements[i]
p_elements = p_elements.reshape(10, 10)
print(p_elements)

[[ 0  1 25  3  4  5  3 48  8 83]
 [41 11  8 79 14 24 17 22  0 19]
 [90 21 22 77 24 25 26 20 34  0]
 [30 19 31 20 34 35 36 37 95 49]
 [56 57 42 11 46 64 46 47 48 49]
 [50 51  3 22 37 29 56 57 51  1]
 [ 5 61 62  4 64 10  0 67 42 69]
 [68 29 27 30 64 49 21 77 42 79]
 [80 36 82 83 21 37  9 19  5 49]
 [90  3 30  0 36 95 56  9 31 68]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [54]:
matrix = rng.integers(10, 100, size=(10, 10))
row_means = np.mean(matrix, axis=1)
print(row_means)

[66.3 52.7 32.  65.1 48.2 53.1 42.5 55.1 59.4 52.6]


#### 59. How to sort an array by the nth column? (★★☆)

In [55]:
matrix = rng.integers(10, 100, size=(10, 10))
column_index = 2
matrix = matrix[matrix[:,column_index].argsort()]
print(matrix)

[[10 27 12 52 38 98 30 68 63 94]
 [57 91 17 20 40 38 14 41 36 59]
 [95 10 32 29 42 58 58 94 23 77]
 [40 37 51 22 42 16 30 15 73 51]
 [64 96 53 63 29 15 65 89 14 53]
 [15 33 54 57 77 10 69 64 51 97]
 [96 20 78 43 79 88 34 97 13 85]
 [91 83 80 72 83 44 87 56 23 62]
 [21 59 86 40 92 42 83 36 75 41]
 [38 32 89 45 62 14 82 26 11 60]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [56]:
matrix = rng.integers(10, 100, size=(10, 10))
matrix[:, 3] = 0
print(matrix)
has_null_columns = np.all(matrix == 0, axis=0)
print(has_null_columns)

[[71 35 80  0 75 85 97 92 23 36]
 [26 22 56  0 75 72 23 32 49 36]
 [35 11 43  0 85 13 75 13 17 45]
 [92 82 61  0 38 96 97 26 49 63]
 [41 54 70  0 51 38 78 50 11 13]
 [38 65 84  0 20 86 35 77 62 76]
 [40 63 10  0 37 54 55 33 19 69]
 [78 59 29  0 69 10 75 56 15 90]
 [23 88 53  0 19 86 26 81 99 85]
 [68 48 36  0 98 55 69 42 69 35]]
[False False False  True False False False False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [57]:
matrix = rng.integers(10, 100, size=10)
print(matrix)
value = 50
distances = np.abs(matrix - value)
nearest_index = np.argmin(distances)
print(matrix[nearest_index])

[54 92 69 86 27 36 59 10 60 58]
54


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [58]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A)
print(B)
print(A.sum() + B.sum())

[[0]
 [1]
 [2]]
[[0 1 2]]
6


#### 63. Create an array class that has a name attribute (★★☆)

In [59]:

class MyArray(np.ndarray):
    def __new__(cls, array, name):
        #create an instance of ndarray class
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
myArray = MyArray(np.arange(9), '0-9array')
print(myArray)
print(myArray.name)


[0 1 2 3 4 5 6 7 8]
0-9array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [60]:
vector = np.arange(50)
indices = rng.integers(0, 50, size=10)
print(vector)
np.add.at(vector, indices, 1)
print(vector)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[ 1  1  2  4  4  5  7  7  8 10 10 11 12 13 14 15 16 18 18 19 20 22 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 39 39 40 42 42 43 44 45 47 48
 48 49]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [61]:
X_SIZE = 10
F_SIZE = 20
X = rng.integers(10, 100, size=X_SIZE)
print('X:', X)
F = np.arange(F_SIZE)
I = rng.integers(0, F_SIZE, size=X_SIZE)
print('I:', I)
np.add.at(F, I, X)
print('F:', F)

X: [56 52 17 19 50 50 96 83 85 23]
I: [11 11  8 11 13 14 17 15 16  1]
F: [  0  24   2   3   4   5   6   7  25   9  10 138  12  63  64  98 101 113
  18  19]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [62]:
I = rng.integers(0, 4, (256, 256, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [63]:
array = rng.integers(10, 100, size=(3, 3, 3, 3))
sum = array.sum(axis=(2, 3))

print(array)
print(sum)

[[[[97 57 32]
   [98 66 58]
   [26 96 82]]

  [[12 50 27]
   [74 76 45]
   [15 49 52]]

  [[80 34 33]
   [27 21 70]
   [24 80 59]]]


 [[[98 85 44]
   [17 34 35]
   [51 26 70]]

  [[13 29 16]
   [20 72 42]
   [64 73 18]]

  [[77 21 27]
   [56 68 39]
   [54 75 71]]]


 [[[67 30 96]
   [55 95 80]
   [56 20 19]]

  [[13 65 81]
   [44 59 64]
   [49 70 84]]

  [[31 70 54]
   [36 83 85]
   [70 87 45]]]]
[[612 400 428]
 [460 347 488]
 [518 529 561]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [64]:
import pandas as pd
D = rng.integers(10, 100, size=10)
print('D:', D)
S = rng.integers(10, size=10)
print('S:', S)
means = pd.Series(D).groupby(S).mean()
print(means)

D: [59 69 86 62 42 79 76 21 89 55]
S: [5 6 6 8 6 2 1 9 8 1]
1    65.500000
2    79.000000
5    59.000000
6    65.666667
8    75.500000
9    21.000000
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [65]:
A = rng.integers(1, 10, size=(5,5))
B = rng.integers(1, 10, size=(5,5))
np.diag(np.dot(A, B))

array([132,  89, 157, 146, 151], dtype=int64)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [66]:
vector = [1, 2, 3, 4, 5]
new_vector = np.repeat(np.zeros(3), 8)
indices = np.arange(0, 24, step=4)
new_vector.put(indices, vector)
print(new_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0. 1. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [67]:
A = rng.integers(1, 10, size=(5,5,3))
B = rng.integers(1, 10, size=(5,5))
print(A * B[:,:,None])

[[[16 24 16]
  [16 32 28]
  [ 8 40 24]
  [ 4  6  6]
  [ 6  6 18]]

 [[ 8 24 32]
  [15 21  3]
  [12  3  6]
  [ 6 16 18]
  [18  9  9]]

 [[16 16 48]
  [48 42 36]
  [64 16 16]
  [72 72 40]
  [42 63 14]]

 [[81 36 72]
  [36 30 48]
  [36 36 54]
  [15 40 15]
  [54 18 18]]

 [[54  9 63]
  [18 18  6]
  [36 24 12]
  [ 4  8  2]
  [ 4  9  5]]]


#### 72. How to swap two rows of an array? (★★★)

In [68]:
R1 = 3
R2 = 5
array = np.arange(100)
matrix = array.reshape(10, 10)
matrix[R1,:] = matrix[R2,:]
print(matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [50 51 52 53 54 55 56 57 58 59]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [69]:
N = 10
vertices = rng.integers(10, 100, size=(N, 3))
segments = np.roll(vertices.repeat(2,axis=1), 1)
segments = segments.reshape(N*3, 2)
segments = list(map(np.unique, segments))
print(segments)

[array([19, 60], dtype=int64), array([51, 60], dtype=int64), array([26, 51], dtype=int64), array([22, 26], dtype=int64), array([22, 41], dtype=int64), array([41, 76], dtype=int64), array([76, 90], dtype=int64), array([85, 90], dtype=int64), array([34, 85], dtype=int64), array([34, 83], dtype=int64), array([83, 94], dtype=int64), array([88, 94], dtype=int64), array([43, 88], dtype=int64), array([28, 43], dtype=int64), array([28, 82], dtype=int64), array([13, 82], dtype=int64), array([13, 15], dtype=int64), array([15, 96], dtype=int64), array([66, 96], dtype=int64), array([38, 66], dtype=int64), array([38, 52], dtype=int64), array([31, 52], dtype=int64), array([31, 80], dtype=int64), array([75, 80], dtype=int64), array([44, 75], dtype=int64), array([44, 84], dtype=int64), array([22, 84], dtype=int64), array([22, 94], dtype=int64), array([24, 94], dtype=int64), array([19, 24], dtype=int64)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [70]:
C = np.bincount(rng.integers(0, 10, size=10))
A = np.repeat(np.arange(len(C)), C)
print('C:', C)
print('np.bincount(A):', np.bincount(A))

C: [0 1 0 3 1 1 0 1 2 1]
np.bincount(A): [0 1 0 3 1 1 0 1 2 1]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [71]:
from numpy.lib.stride_tricks import sliding_window_view

array = np.arange(10)
print(sliding_window_view(array, window_shape=3).mean(axis=-1))


[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [72]:
array = np.arange(10)
print(sliding_window_view(array, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [73]:
bool_array = rng.integers(0,2,10)
np.logical_not(bool_array, out=bool_array)
print(bool_array)

float_array = rng.uniform(-1.0,1.0,10)
np.negative(float_array, out=float_array)
print(float_array)

[1 0 1 1 0 1 0 0 1 1]
[-0.5481524  -0.91683804  0.6707601  -0.97574594  0.89177213 -0.15428042
 -0.93144382 -0.76518698  0.86697518 -0.94908868]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [74]:
P0 = rng.integers(10, size=(10, 2))
P1 = rng.integers(10, size=(10, 2))
P = [7, 9]

centers = np.add(P0, P1)/2
distances = np.sqrt(np.sum(np.subtract(P, centers)**2, axis=-1))
print(distances)

[4.52769257 6.57647322 7.90569415 6.5        3.80788655 5.52268051
 4.03112887 6.10327781 6.72681202 6.96419414]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [75]:
P0 = rng.integers(10, size=(10, 2))
P1 = rng.integers(10, size=(10, 2))
P = rng.integers(10, size=(10, 2))

P = P[:, np.newaxis, :]
centers = centers[np.newaxis, :, :]

centers = np.add(P0, P1)/2
distances = np.sqrt(np.sum(np.subtract(P, centers)**2, axis=-1))
print(distances)

[[ 5.22015325  7.43303437  2.5         6.36396103  7.07106781 10.30776406
   5.65685425  6.5         9.60468636  3.90512484]
 [ 4.03112887  5.31507291  0.5         4.30116263  5.          8.32165849
   3.60555128  4.60977223  7.43303437  2.06155281]
 [ 6.02079729  7.5         2.6925824   6.51920241  6.32455532 10.54751155
   5.83095189  5.59016994  9.55248659  4.27200187]
 [ 6.26498204  3.35410197  5.02493781  3.53553391  1.          6.02079729
   3.60555128  2.06155281  4.03112887  4.60977223]
 [ 4.03112887  5.31507291  0.5         4.30116263  5.          8.32165849
   3.60555128  4.60977223  7.43303437  2.06155281]
 [ 4.9244289   2.06155281  4.27200187  2.12132034  2.23606798  5.02493781
   2.23606798  3.04138127  3.35410197  3.5       ]
 [ 5.31507291  4.03112887  3.04138127  3.53553391  2.          7.15891053
   3.16227766  1.80277564  5.59016994  3.20156212]
 [ 5.85234996  2.5         7.43303437  3.53553391  6.          1.11803399
   4.24264069  7.01783442  1.11803399  6.02079729]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [76]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = sliding_window_view(Z, window_shape=4)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [77]:
matrix = rng.integers(10, 100, size=(5, 5))
np.linalg.matrix_rank(matrix)

5

#### 83. How to find the most frequent value in an array?

In [78]:
array = rng.integers(10, 100, size=100)
print(array)
print(np.bincount(array).argmax())

[79 64 73 96 92 91 62 72 64 30 26 91 65 65 43 93 24 83 34 39 68 93 87 63
 54 20 28 75 77 21 46 27 40 32 34 55 84 33 44 26 86 75 37 87 70 89 23 36
 50 47 23 26 52 70 34 67 51 97 60 34 32 62 15 29 24 20 91 83 16 32 50 74
 49 50 88 96 41 33 24 56 83 31 65 10 21 97 39 74 64 39 50 50 25 93 19 73
 56 62 91 88]
50


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [79]:
matrix = rng.integers(10, 100, size=(10, 10))
print(matrix)
print(sliding_window_view(matrix, window_shape=(3, 3)))

[[92 69 70 99 95 91 39 38 18 48]
 [69 88 93 64 68 64 77 48 42 13]
 [81 85 43 17 51 89 31 29 98 11]
 [76 69 36 59 49 14 74 18 56 27]
 [40 38 96 21 49 51 91 81 35 76]
 [49 26 13 99 28 67 60 43 47 50]
 [31 53 46 80 39 17 91 47 31 35]
 [11 48 31 99 59 32 22 43 57 18]
 [75 51 16 14 65 46 27 22 48 91]
 [59 51 29 35 38 34 69 50 90 89]]
[[[[92 69 70]
   [69 88 93]
   [81 85 43]]

  [[69 70 99]
   [88 93 64]
   [85 43 17]]

  [[70 99 95]
   [93 64 68]
   [43 17 51]]

  [[99 95 91]
   [64 68 64]
   [17 51 89]]

  [[95 91 39]
   [68 64 77]
   [51 89 31]]

  [[91 39 38]
   [64 77 48]
   [89 31 29]]

  [[39 38 18]
   [77 48 42]
   [31 29 98]]

  [[38 18 48]
   [48 42 13]
   [29 98 11]]]


 [[[69 88 93]
   [81 85 43]
   [76 69 36]]

  [[88 93 64]
   [85 43 17]
   [69 36 59]]

  [[93 64 68]
   [43 17 51]
   [36 59 49]]

  [[64 68 64]
   [17 51 89]
   [59 49 14]]

  [[68 64 77]
   [51 89 31]
   [49 14 74]]

  [[64 77 48]
   [89 31 29]
   [14 74 18]]

  [[77 48 42]
   [31 29 98]
   [74 18 56]]

  [[48 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [80]:
class SymetricMatrix(np.ndarray):
    def __new__(cls, array):
        obj = np.asarray(array).view(cls)
        obj = np.maximum(array, array.transpose())
        return obj

array = np.arange(16).reshape(4, 4)
S = SymetricMatrix(array)
print(S)
        

[[ 0  4  8 12]
 [ 4  5  9 13]
 [ 8  9 10 14]
 [12 13 14 15]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [81]:
P = 10
N  = 10
matrices = np.arange(1000).reshape((P,N,N))
vectors = np.arange(100).reshape((P,N,1))
sum = np.tensordot(matrices, vectors, axes=[[0, 2], [0, 1]])
print(S)

[[ 0  4  8 12]
 [ 4  5  9 13]
 [ 8  9 10 14]
 [12 13 14 15]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [82]:
array = np.arange(16*16).reshape((16, 16))
N = 4
print(sliding_window_view(array, window_shape=(N, N))[::N, ::N].sum(axis=(-2, -1)))

[[ 408  472  536  600]
 [1432 1496 1560 1624]
 [2456 2520 2584 2648]
 [3480 3544 3608 3672]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [83]:
array = rng.integers(10, 100, size=50)
N = 10
print(array[np.argsort(array)[-N:]])

[67 70 70 76 76 82 86 87 93 99]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [84]:

arrays = [[5, 6, 2], [9, 4, 3], [7, 3, 8]]
n = len(arrays)
result = np.zeros((n, n), dtype=np.ndarray)

for i in range(n):
    for j in range(n):
        result[i, j] = np.dot(arrays[i], arrays[j])

print(result)


[[65 75 69]
 [75 106 99]
 [69 99 122]]


#### 91. How to create a record array from a regular array? (★★★)

In [85]:
regular_array = np.array([(1, 'Name1', 45), (2, 'Name2', 36), (3, 'Name3', 22)])
record_array = np.rec.fromarrays(regular_array, names='id, name, age')
print(record_array)

[('1', '2', '3') ('Name1', 'Name2', 'Name3') ('45', '36', '22')]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [86]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.2 s ± 26.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
173 ms ± 7.15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
115 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [246]:
A = rng.integers(0, 10,(8,3))
B = rng.integers(0, 10,(2,2))
matching_rows = []

for row in B:
    count = np.sum(np.isin(A, row, assume_unique=False), axis=1)
    matching_rows.append(count)

print('A:', A)
print('B:', B)
print(matching_rows)

A: [[7 4 1]
 [2 1 9]
 [8 5 7]
 [8 6 8]
 [8 6 4]
 [1 0 4]
 [3 5 4]
 [6 4 4]]
B: [[9 1]
 [5 2]]
[array([1, 2, 0, 0, 0, 1, 0, 0]), array([0, 1, 1, 0, 0, 0, 1, 0])]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [147]:
matrix = rng.integers(0, 10, size=(10, 3))
equal_values = np.all(matrix == matrix[:, [0]], axis=1)
print(matrix)
print(equal_values)

[[5 2 6]
 [3 9 8]
 [3 3 1]
 [6 4 7]
 [3 9 7]
 [4 2 6]
 [6 7 7]
 [5 3 9]
 [5 9 7]
 [7 7 7]]
[False False False False False False False False False  True]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [292]:
int_vector = np.arange(0, 100, 4)
binary_vector = ((int_vector.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(binary_vector[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 1 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 1 1 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 1 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 1 0 1 1 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 1 1 0 1 0 0]
 [0 0 1 1 1 0 0 0]
 [0 0 1 1 1 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0]
 [0 1 0 0 1 1 0 0]
 [0 1 0 1 0 0 0 0]
 [0 1 0 1 0 1 0 0]
 [0 1 0 1 1 0 0 0]
 [0 1 0 1 1 1 0 0]
 [0 1 1 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [281]:
matrix = rng.integers(0, 10, size=(10, 10))
matrix[2,:] = np.arange(10)
matrix[6,:] = np.arange(10)
matrix[7,:] = np.arange(10)
unique_rows = np.unique(matrix, axis=0)
print(unique_rows)

[[0 1 2 3 4 5 6 7 8 9]
 [1 3 1 8 9 0 1 7 8 9]
 [3 0 1 6 2 3 3 7 2 7]
 [3 6 9 7 4 8 9 3 3 6]
 [3 7 0 6 4 9 7 8 5 8]
 [5 0 7 9 9 5 9 4 0 3]
 [5 2 9 6 2 9 0 9 9 8]
 [6 2 1 0 8 9 6 8 1 2]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [290]:
A = rng.integers(100, size=100)
B = rng.integers(100, size=100)

print('inner:', np.einsum('i,i->', A, B))
print('outer:', np.einsum('i,j->ij', A, B))
print('sum:', np.einsum('i->', A))
print('mul:', np.einsum('i,i->i', A, B))

inner: 229164
outer: [[2511 2322  162 ...  567 1269  648]
 [9207 8514  594 ... 2079 4653 2376]
 [6789 6278  438 ... 1533 3431 1752]
 ...
 [7440 6880  480 ... 1680 3760 1920]
 [6603 6106  426 ... 1491 3337 1704]
 [1860 1720  120 ...  420  940  480]]
sum: 4971
mul: [2511 8514  438 8448  960 3843  395 2139  540 5292 2079 2352 1281 4554
 3116 1152 2808  136 6248   44 4316 5676  341  756 1518 2920 1148 3621
 3577 3003 3456 3536  442 5720 2581 3150  264    0  384  336  322 7469
 5994 4756   65 1365  768 1512  450    0  252 4189 3458  295 2436 3285
 1925 4331 5016 5504 3705  923   96  171 2278 2048 1230 2059  216 4779
 1445 6789 6231  234 2730   39 3910   11  784 4233  187  100  510 2850
  114 3139 2400 2400 1785  880 2470 1328  146  216  104 2970 1170 1680
 3337  480]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [293]:
X = np.array([0, 1, 3, 6, 9])
Y = np.array([0, 2, 4, 3, 7])

n_samples = 10
total_distance = np.sum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
step_size = total_distance / (n_samples - 1)

sample_points = [(X[0], Y[0])]

accumulated_distance = 0
current_index = 0

while len(sample_points) < n_samples:
    distance = np.sqrt((X[current_index + 1] - X[current_index])**2 + 
                       (Y[current_index + 1] - Y[current_index])**2)
     
    if accumulated_distance + distance >= step_size:
        fraction = (step_size - accumulated_distance) / distance
        # Interpolate and add the new sample point
        new_x = X[current_index] + fraction * (X[current_index + 1] - X[current_index])
        new_y = Y[current_index] + fraction * (Y[current_index + 1] - Y[current_index])
        sample_points.append((new_x, new_y))
        
        accumulated_distance = 0
    else:
        # Continue accumulating distance
        accumulated_distance += distance
        current_index += 1

print(sample_points)

[(0, 0), (0.6572436226600262, 1.3144872453200525), (0.6572436226600262, 1.3144872453200525), (0.6572436226600262, 1.3144872453200525), (0.6572436226600262, 1.3144872453200525), (0.6572436226600262, 1.3144872453200525), (0.6572436226600262, 1.3144872453200525), (0.6572436226600262, 1.3144872453200525), (0.6572436226600262, 1.3144872453200525), (0.6572436226600262, 1.3144872453200525)]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [344]:
X = rng.integers(0, 10, size=(8, 8))
N = 36

row_sums = np.sum(X, axis=1)
valid_indices = np.where(row_sums == N)
valid_rows = X[valid_indices]
print('X:', X)
print('sums:', row_sums)
print('valid_rows:', valid_rows)

X: [[3 2 1 6 6 9 9 0]
 [8 2 8 1 3 8 8 6]
 [1 0 7 3 4 0 6 3]
 [8 6 1 5 6 1 3 0]
 [2 6 8 6 0 9 4 3]
 [7 5 0 0 1 8 4 0]
 [3 4 8 2 1 3 4 9]
 [3 9 8 9 4 2 2 2]]
sums: [36 44 24 30 38 25 34 39]
valid_rows: [[3 2 1 6 6 9 9 0]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [355]:
X = rng.integers(0, 10000, size=1)
N = 1000
means = np.zeros(N)

for i in range(N):
    sample = rng.choice(X, len(X), replace=True)
    means[i] = np.mean(sample)

lower_bound = 2.5
upper_bound = 97.5
confidence_interval = np.percentile(means, [lower_bound, upper_bound])
print(confidence_interval)

[2633. 2633.]
